[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "a_maze_ing"
version = "1.0.0"
description = "Interactive terminal-based maze generator and animator"
requires-python = ">=3.13"
dependencies = []

[tool.setuptools]
packages = ["app", "cli", "display", "mazegen"]
py-modules = ["a_maze_ing"]
